Repository zowe/zlux-editor, pull requests merged in 2023-04, with the labels that each got.

#322 Consolidate functions to utils service, fix app2app openDataset function
  CHANGELOG.md
  webClient/src/app/app.component.ts
  webClient/src/app/editor/frame/frame.component.ts
  webClient/src/app/editor/project-tree/project-tree.component.ts
  webClient/src/app/shared/editor-control/editor-control.service.ts
  webClient/src/app/shared/utils.service.ts
Labels: size/M

#324 Update version
  webClient/package-lock.json
  webClient/package.json
Labels: size/XS

#325 Fix App2App Timing Issues With File Tree Operations
  webClient/package-lock.json
  webClient/package.json
  webClient/src/app/editor/project-tree/project-tree.component.ts
Labels: size/S
